language: go
go:
  - 1.11.x
  - 1.12.x
os:
  - linux
  - osx

install:
  - go get -u github.com/golang/dep/cmd/dep
  - go get github.com/onsi/ginkgo/ginkgo
  - go get github.com/onsi/gomega/...
  - dep ensure
  - export PATH=$PATH:$HOME/gopath/bin

script: ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --cover --trace --race --compilers=2
