language: go
go:
  - 1.11.x
  - 1.12.x
  - master
os:
  - linux
  - osx

install:
  - dep ensure
  - export PATH=$PATH:$HOME/gopath/bin

script: ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --cover --trace --race --compilers=2
